name: "liquid-website"

services:
  website:
    build: .
    image: "liquid-website:latest"
    container_name: "liquid-website"
    restart: unless-stopped
    ports:
      - "8084:80"
    networks:
      - web

networks:
  web:
    external: true